"""empty message

Revision ID: dd87b4facc85
Revises: 
Create Date: 2020-07-05 15:43:00.864874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd87b4facc85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_cidade')
    op.drop_table('tb_feriado')
    op.drop_table('tb_estado')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_estado',
    sa.Column('prefixo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sigla', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('prefixo', name='tb_estado_pkey')
    )
    op.create_table('tb_feriado',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('poder', sa.String(), autoincrement=False, nullable=False),
    sa.Column('ano', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('mes', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('dia', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.String(), autoincrement=False, nullable=False),
    sa.Column('local', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tb_feriado_pkey')
    )
    op.create_table('tb_cidade',
    sa.Column('codigo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('codigo', name='tb_cidade_pkey')
    )
    # ### end Alembic commands ###
